services:
  wowza:
    image: wowzamedia/wowza-streaming-engine-linux:4.9.3
    entrypoint: /sbin/entrypoint.sh
    ports:
      - "1935:1935" # Wowza RTMP port
      - "8086:8086" # Wowza admin api
      - "8087:8087" # Rest API
      - "8088:8088" # Wowza admin UI
